#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Saturdays4Ai  # The title of the book. Will be placed in the left navbar.
author                      : SaturdaysAi  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
repository:
  url                       : https://github.com/Saturdays4Ai/Sesions_book  # Online location of your book
  path_to_book              : ./Saturdays4Ai_book  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  colab_url: "https://colab.research.google.com"
